apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  # REPLACE THESE VALUES WITH YOUR ACTUAL SECRETS
  NODE_ENV: "production"
  PORT: "5000"
  MONGODB_URI: "mongodb+srv://garhasaab001_db_user:WQge8iTiIiBZAqIT@keanacm.6g7v8oc.mongodb.net/?appName=keanacm"
  JWT_SECRET: "KeanACMSecret"
  # Add other env vars from your .env file here
