apiVersion: v1
kind: Service
metadata:
  name: kean-acm-backend-service
spec:
  selector:
    app: kean-acm-backend
  ports:
    - protocol: TCP
      port: 80 # Port exposed externally
      targetPort: 5000 # Port the container is listening on
  type: LoadBalancer # Use LoadBalancer for local testing (Docker Desktop/Minikube) or Cloud
